os:
  editPreset: "nvim"
  editInTerminal: true

disableStartupPopups: true
notARepository: skip
gui:
 mouseEvents: true
  # Use the mocha catppuccin theme
 theme:
   activeBorderColor:
     - '#89b4fa'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'
    # selectedLineBgColor:
    #   - black
    # selectedLineFgColor:
    #   - white
git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side --line-numbers

services:
  "bitbucket.dev.kiwigrid.com": "bitbucketServer:bitbucket.dev.kiwigrid.com"
customCommands:
  - key: "O"
    context: "commits"
    description: "Open Pull Request in Browser"
    command: >
      sh -c '
        msg="{{.SelectedCommit.Name}}";
        sha="{{.SelectedCommit.Sha}}";
        remote=$(git config --get remote.origin.url);
        project=$(echo "$remote" | sed -E "s|.*[:/]([^/]+)/.*|\1|" | tr "[:lower:]" "[:upper:]");
        repo=$(basename -s .git $(echo "$remote" | sed -E "s|.*/([^/]+)(\\.git)?$|\1|"));
        pr=$(echo "$msg" | grep -oE "#[0-9]+" | tr -d "#");
        if [ -n "$pr" ]; then
          open "https://bitbucket.dev.kiwigrid.com/projects/$project/repos/$repo/pull-requests/$pr/overview";
        else
          echo "No PR number found in commit message." >&2;
        fi
      '
  - key: "O"
    context: "subCommits"
    description: "Open Pull Request in Browser"
    command: >
      sh -c '
        msg="{{.SelectedCommit.Name}}";
        sha="{{.SelectedCommit.Sha}}";
        remote=$(git config --get remote.origin.url);
        project=$(echo "$remote" | sed -E "s|.*[:/]([^/]+)/.*|\1|" | tr "[:lower:]" "[:upper:]");
        repo=$(basename -s .git $(echo "$remote" | sed -E "s|.*/([^/]+)(\\.git)?$|\1|"));
        pr=$(echo "$msg" | grep -oE "#[0-9]+" | tr -d "#");
        if [ -n "$pr" ]; then
          open "https://bitbucket.dev.kiwigrid.com/projects/$project/repos/$repo/pull-requests/$pr/overview";
        else
          echo "No PR number found in commit message." >&2;
        fi
      '
