
command_timeout = 3600

# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 

format = """
$os\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character
"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ── Spacer to push time to the right ─────────────────
[fill]
symbol = " "         # plain spaces
style  = ""          # no bg so you don't get a colored bar

[time]
disabled = false
time_format = "%H:%M"
style = "fg:lavender bg:black"
format = "[ ](black)[ $time]($style)[](black)"

[os.symbols]
Macos = " "
Debian = "󰣚"

[directory]
style = "sapphire"
format = "[ $path ]($style)"
truncation_length = 5
# truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[os]
disabled = false
style = "bg:none fg:text"

[git_branch]
symbol = "[](black) "
style = "fg:lavender bg:black"
format =  'on [$symbol$branch]($style)[](black)'

[git_status]
format = ' [($all_status$ahead_behind )]($style)'

[line_break]
disabled = false 

[character]
disabled = false
success_symbol = '[➜](bold fg:green)'
error_symbol = '[➜](bold fg:red)'
vimcmd_symbol = '[](bold fg:yellow)'

[cmd_duration]
disabled = false
show_milliseconds = false
style = "fg:lavender bg:black"
format = "[](black)[󰔛 $duration]($style)[](black)"
show_notifications = true
min_time_to_notify = 45000
