"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
[](text)\
$os\
$username\
[](bg:blue fg:text)\
$directory\
[](bg:soft_yellow fg:blue)\
$git_branch\
$git_status\
[](fg:soft_yellow )\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:text fg:crust"

[os.symbols]
Macos = "󰀵"

[username]
show_always = true
style_user = "bg:text fg:crust"
style_root = "bg:text fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# [directory.substitutions]
# "~/Documents" = "󰈙"
# "~/Downloads" = ""
# "~/Music" = "󰝚"
# "~/Pictures" = ""
# "~/.config" = ""
# "~/kiwigrid/projects" = " "
# "~" = ""

[git_branch]
symbol = ""
style = "bg:soft_yellow"
format = '[[ $symbol $branch ](fg:crust bg:soft_yellow)]($style)'

[git_status]
style = "bg:soft_yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:soft_yellow)]($style)'
# Define symbols for different states
conflicted = " "   # nf-md-source_merge
staged     = " "   # nf-fa-plus
modified   = " "   # nf-fa-pencil
renamed    = " "   # nf-oct-diff_renamed
deleted    = " "   # nf-oct-diff_removed
untracked  = " "   # nf-mdi-file_alert
stashed    = " "   # nf-mdi-database
ahead      = " "   # nf-oct-arrow_up
behind     = " "   # nf-oct-arrow_down
diverged   = " "   # nf-mdi-source_branch
up_to_date = " "   # nf-mdi-check_bold

[rust]
symbol = ""
style = "bg:soft_green"
format = '[[ $symbol( $version) ](fg:crust bg:soft_green)]($style)'

[java]
symbol = " "
style = "bg:soft_green"
format = '[[ $symbol( $version) ](fg:crust bg:soft_green)]($style)'

[python]
symbol = ""
style = "bg:soft_green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:soft_green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:text)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = false
style = "fg:lavender"
format = "[  $duration ]($style)"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"         # bright silver (now main silver)
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# custom mellow tones
soft_yellow = "#e6d89a"
soft_green  = "#8fcea1"

